AppBundle\Entity\Genre:
    type: entity
    table: null
    repositoryClass: AppBundle\Entity\GenreRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        genre:
            type: string
            length: 255
    lifecycleCallbacks: {  }
