AppBundle\Entity\Genre:
    type: entity
    table: genre
    repositoryClass: AppBundle\Entity\Repository\GenreRepository
    id:
        genreid:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        genre:
            type: string
            length: 255
    lifecycleCallbacks: {  }
