AppBundle\Entity\Genre:
    type: entity
    table: genre
    repositoryClass: AppBundle\Entity\Repository\GenreRepository
    id:
        genreid:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        genre:
            type: string
            length: 255

    oneToMany:
        children:
            targetEntity: Genre
            mappedBy: parent
            joinColumn:
                referencedColumnName: genreid
    manyToOne:
        parent:
            targetEntity: Genre
            inversedBy: children
            joinColumn:
                referencedColumnName: genreid
    lifecycleCallbacks: {  }
